### ISSUE TITLE
Build error if AndroidX is used

### ISSUE THREAD

**Issue by Boehrsi** [PonnamKarthik/FlutterToast#44]
If the library is used within a project which uses AndroidX in the native Android part of the Flutter app, FlutterToast won't compile. The following error appears:

> Launching lib/main.dart on SM G930F in debug mode...
> Initializing gradle...
> Resolving dependencies...
> Gradle task 'assembleDebug'...
> /home/daniel/.pub-cache/hosted/pub.dartlang.org/fluttertoast-2.2.3/android/src/main/java/io/github/ponnamkarthik/toast/fluttertoast/FluttertoastPlugin.java:9: error: package android.support.v4.content does not exist
> import android.support.v4.content.ContextCompat;
>                                  ^
> /home/daniel/.pub-cache/hosted/pub.dartlang.org/fluttertoast-2.2.3/android/src/main/java/io/github/ponnamkarthik/toast/fluttertoast/FluttertoastPlugin.java:70: error: cannot find symbol
>           Drawable shapeDrawable = ContextCompat.getDrawable(ctx, R.drawable.toast_bg);
>                                    ^
>   symbol:   variable ContextCompat
>   location: class FluttertoastPlugin
> 2 errors
> 
> FAILURE: Build failed with an exception.
> 
> * What went wrong:
> Execution failed for task ':fluttertoast:compileDebugJavaWithJavac'.
> Compilation failed; see the compiler error output for details.

The reason is that android.support.v4.content doesn't exists and androidx.core.content should get used instead. I changed the mentioned parts in this pull request (https://github.com/PonnamKarthik/FlutterToast/pull/45). Due to a lack of time I wasn't able to test if also non-AndroidX apps, so apps that still use the com.android.support:appcompat-vXYZ, work completely fine with the suggest changes.

**Comment by PonnamKarthik** [comment]
fixed v2.2.4

**Comment by giaur500** [comment]
Not fixed:

`fluttertoast/FluttertoastPlugin.java:14: error: package android.support.v4.content does not exist`
```
fluttertoast-2.2.11/android/src/main/java/io/github/ponnamkarthik/toast/fluttertoast/FluttertoastPlugin.java:107: error: cannot find symbol
          Drawable shapeDrawable = ContextCompat.getDrawable(ctx, R.drawable.toast_bg);
```

**Comment by PonnamKarthik** [comment]
@giaur500 if your project uses androidX please use fluttertoast version 2.2.4 or 2.2.5

**Comment by giaur500** [comment]
Latest version again broken? 2.2.11 is newer than 2.2.4

**Comment by Boehrsi** [comment]
@giaur500 the problem is that either AndroidX or the normal support library can be supported. Sadly not both at once. So you have to use the older 2.2.4 or 2.2.5 versions if you use AndroidX. The newer versions are using the normal support libraries as it seems that there are some general problems with Flutter and AndroidX right now.

**Comment by giaur500** [comment]
Well, some others started to drop deprecated support libraries, like shared prefs plugin. I think you should consider to swap it, deprecated libraries supported with older plugin version and androidx in latest version.

Btw I am unable to force old version, Android Studios keeps downloading latest one, even if I set to older, thus I can't use toast at all

**Comment by Boehrsi** [comment]
I totally get your point. I'm also trying to use recent stuff, which was the reason for my initial PR to adjust the imports to AndroidX. 
Regarding the mentioned switch (older FlutterToast versions stay on support.v4, while newer ones upgrade to AndroidX), this is something only the creator of this project can decide and I personally think to much other libraries are sill using support.v4 (sadly).

Regarding your problem with forcing a version, have you tried using:
`# add this line to your dependencies
fluttertoast: 2.2.5
`
Important is the missing "^" at the start of the import.

**Comment by giaur500** [comment]
Well this is a mess, this one of reasons I am generally against multiplatform solutions that use one abstraction layer above native api. Now some plugins (firebase, sharedprefs etc) switched to androidx, some others keep using deprecated api. Either I need to use outdated plugins (potentially, with security problems and missing features) or I will end with conflits impossible to solve unless I fork plugin and make my own changes.

**Comment by PonnamKarthik** [comment]
@giaur500 

Finally, plugin is now migrated to android please use `3.0.0`
